spring.datasource.url=jdbc:postgresql://postgres:5432/smart_parking_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.data.redis.host=redis
spring.data.redis.port=6379

spring.cache.type=redis

logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.cache=TRACE

spring.kafka.bootstrap-servers=kafka:9092

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projectsiddhijava@gmail.com
spring.mail.password=uvcqyrthdpvjjxel

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true